[[tags]]
names = ["Universidade Federal do Pará", "UFPA"]

[[tags]]
names = ["Universidade do Estado do Pará", "UEPA"]

[[tags]]
names = ["Ciência da Computação"]

[[tags]]
names = ["Engenharia da Computação"]

[[tags]]
names = ["Sistemas de Informação"]

[[tags]]
names = ["Python"]

[[tags]]
names = ["C"]
